version: "3"

services:
  app:
    build:
      context: ./
    tty: true
    links:
      - mysql
    restart: always
    volumes:
      - ./:/app
    ports:
      - ${HTTP_PORT}:8080

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - database:/var/lib/mysql
      - ./docker/db:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  database: